<?php
  include("../models/Fazenda.php");
  include("../models/Produtor.php");
  include("../models/Endereco.php");
  include("../models/Producao.php");
  include("../models/Produto.php");
  include("../models/Estoque.php");
  include("../models/Transacao.php");
  include("../models/Comprador.php");
  include("../models/Transportadora.php");
  include("../models/Posse.php");
  include("../models/Enderecos.php");
  $fazenda = new Fazenda();
  $produtor = new Produtor();
  $endereco = new Endereco();
  $produto = new Produto();
  $comprador = new Comprador();
  $transportadora = new Transportadora();
  $producao = new Producao();
  $estoque = new Estoque();
  $transacao = new Transacao();
  $posse = new Posse();
  $enderecos = new Enderecos();
  //$fazenda->insertNew("Fazenda de Corno", "Cornolandia", 24, "69.24:24.69");
  //$produtor->insertNew("24692469246929", "Jose Corno", "3599692422");
  //$endereco->insertNew("24246969", "Galhos", "Rua dos Chifrudos", "11", "Proximo a casa de carnes touro bravo");
  //$produto->insertNew("Galhada", "De alce", "50cm");
  //$comprador->insertNew("22446699246929", "Ada Nada", "88626011", "24246969", "Tilambuco", "Rua dos anos", "69", "Perto da loja Patin Rabá");
  //$transportadora->insertNew("22446699246928", "Taj Mahal", "6969696969", "24246969", "Butao", "Rua da Cruz Vermelha", "24", "Perto da loja escala");
  //$estoque->insertNew(0, 1);
  //$producao->insertNew(100, "2019", 1, 1, 1, 1);
  //$estoque->sumQuantidade(1, 100);
  //$transacao->insertNew(10000, 100, 1, 1, 1);
  //$estoque->sumQuantidade(1, -100);
  //$posse->insertNew(1, 1);
  $enderecos->insertNew(1, 1);
  echo "Deu <br />";
?>
